# Generated by Django 4.2.3 on 2023-07-27 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ativo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ativo',
            name='corretora',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='ativo.corretora'),
        ),
    ]
