# Generated by Django 4.2.3 on 2023-07-27 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ativo', '0002_alter_ativo_corretora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ativo',
            name='corretora',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='corretora', to='ativo.corretora'),
        ),
    ]
