# Generated by Django 4.2.3 on 2023-09-25 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ativo', '0003_alter_ativo_corretora'),
    ]

    operations = [
        migrations.AddField(
            model_name='ativo',
            name='criado_em',
            field=models.DateField(auto_now=True),
        ),
    ]
