# Generated by Django 4.2.3 on 2023-09-25 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ativo', '0004_ativo_criado_em'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ativo',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
